export const DA_NANG_WARDS = [
    "Hải Châu",
    "Thanh Khê",
    "Sơn Trà",
    "Ngũ Hành Sơn",
    "Liên Chiểu",
    "Cẩm Lệ",
    "Hòa Vang",
    "Hải Vân",
    "Hòa Khánh",
    "Hòa Cường",
    "Bàn Thạch",
    "Hòa Xuân",
    "An Hải",
    "An Khê",
    "Tam Kỳ",
    "Hương Trà",
    "Quảng Phú",
    "Hội An Tây",
    "Hội An Đông",
    "Điện Bàn",
    "Điện Bàn Bắc",
    "An Thắng",
    "Điện Bàn Đông",
  ];